namespace ReclutaCVData.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ModCandidatoCamposCompletos : DbMigration
    {
        public override void Up()
        {
            AddColumn("public.Candidato", "EstadoCivil", c => c.String());
            AddColumn("public.Candidato", "LugarNacimiento", c => c.String());
            AddColumn("public.Candidato", "GeneralesComentarios", c => c.String());
            AddColumn("public.Candidato", "Compañia", c => c.String());
            AddColumn("public.Candidato", "MotivoDeSeparacion", c => c.String());
            AddColumn("public.Candidato", "CompetenciasOHabilidades", c => c.String());
            AddColumn("public.Candidato", "TecnologiasQueDomina", c => c.String());
            AddColumn("public.Candidato", "SoftwareQueDomina", c => c.String());
            AddColumn("public.Candidato", "NivelDeIngles", c => c.String());
            AddColumn("public.Candidato", "SolicitudPersonalFolio", c => c.Int());
            AddColumn("public.Candidato", "PuestoClave", c => c.Int());
            AddColumn("public.Candidato", "PuestoNombre", c => c.String());
            AddColumn("public.Candidato", "ProyectoNombre", c => c.String());
            AddColumn("public.Candidato", "FechaDeRecepcionCurriculum", c => c.DateTime());
            AddColumn("public.Candidato", "FechaPreentrevistaTelefonica", c => c.DateTime());
            AddColumn("public.Candidato", "FechaRecepcionSolicitudRegistro", c => c.DateTime());
            AddColumn("public.Candidato", "BolsaOtra", c => c.String());
            AddColumn("public.Candidato", "RolOtro", c => c.String());
            AddColumn("public.Candidato", "ExpectativaEconomica", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("public.Candidato", "ReclutamientoComentarios", c => c.String());
            AddColumn("public.Candidato", "ExamenPsicometricoNombre", c => c.String());
            AddColumn("public.Candidato", "ExamenPsicometricoResultados", c => c.String());
            AddColumn("public.Candidato", "ExamenPsicometricoObservaciones", c => c.String());
            AddColumn("public.Candidato", "ExamenProgramacionFecha", c => c.DateTime());
            AddColumn("public.Candidato", "ExamenProgramacionIpComputadora", c => c.String());
            AddColumn("public.Candidato", "ExamenProgramacionId", c => c.String());
            AddColumn("public.Candidato", "ExamenProgramacionUmlCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionUmlTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionAdooCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionAdooTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionPooCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionPooTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionLogicaCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionLogicaTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionWebCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionWebTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionJavascriptCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionJavascriptTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionScrumCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionScrumTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionTecnologiaCalificacion", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionTecnologiaTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenProgramacionRango", c => c.String());
            AddColumn("public.Candidato", "ExamenAnalistaFecha", c => c.DateTime());
            AddColumn("public.Candidato", "ExamenAnalistaIpComputadora", c => c.String());
            AddColumn("public.Candidato", "ExamenAnalistaTeoricoId", c => c.String());
            AddColumn("public.Candidato", "ExamenAnalistaTeoricoAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAnalistaTeoricoTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAnalistaTeoricoRango", c => c.String());
            AddColumn("public.Candidato", "ExamenAnalistaPracticoId", c => c.String());
            AddColumn("public.Candidato", "ExamenAnalistaPracticoNumeroCaso", c => c.Int());
            AddColumn("public.Candidato", "ExamenAnalistaPracticoAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAnalistaPracticoTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAnalistaPracticoRango", c => c.String());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasFecha", c => c.DateTime());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasIpComputadora", c => c.String());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoId", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoRango", c => c.String());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasPracticoId", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasPracticoCalificacion", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("public.Candidato", "ExamenIngenieroPruebasPracticoPuntos", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasPracticoRango", c => c.String());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasSqlTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenIngenieroPruebasSqlCalificacion", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("public.Candidato", "ExamenAdministradorProyectoFecha", c => c.DateTime());
            AddColumn("public.Candidato", "ExamenAdministradorProyectoIpComputadora", c => c.String());
            AddColumn("public.Candidato", "ExamenAdministradorProyectoId", c => c.Int());
            AddColumn("public.Candidato", "ExamenAdministradorProyectoAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAdministradorProyectoTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenAdministradorProyectoRango", c => c.String());
            AddColumn("public.Candidato", "ExamenPracticoSoporteBdFecha", c => c.DateTime());
            AddColumn("public.Candidato", "ExamenPracticoSoporteBdAciertos", c => c.Int());
            AddColumn("public.Candidato", "ExamenPracticoSoporteBdTotalReactivos", c => c.Int());
            AddColumn("public.Candidato", "ExamenPracticoSoporteBdRango", c => c.String());
            AddColumn("public.Candidato", "EntrevistaCapitalHumanoFecha", c => c.DateTime());
            AddColumn("public.Candidato", "EntrevistaCapitalHumanoComentarios", c => c.String());
            AddColumn("public.Candidato", "EntrevistaCoordinadorYEquipoTecnicoFecha", c => c.DateTime());
            AddColumn("public.Candidato", "EntrevistaCoordinadorYEquipoTecnicoComentarios", c => c.String());
            AddColumn("public.Candidato", "EntrevistaInglesFecha", c => c.DateTime());
            AddColumn("public.Candidato", "EntrevistaInglesComentarios", c => c.String());
            AddColumn("public.Candidato", "EntrevistaGerenteAreaFecha", c => c.DateTime());
            AddColumn("public.Candidato", "EntrevistaGerenteAreaComentarios", c => c.String());
            AddColumn("public.Candidato", "VeredictoFinal", c => c.Int());
            AddColumn("public.Candidato", "VeredictoFinalNivelIdentificado", c => c.String());
            AddColumn("public.Candidato", "VeredictoFinalComentarios", c => c.String());
            AddColumn("public.Candidato", "PropuestaEconomicaFecha", c => c.DateTime());
            AddColumn("public.Candidato", "PropuestaEconomicaSueldo", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("public.Candidato", "PropuestaEconomicaComentarios", c => c.String());
            AddColumn("public.Candidato", "IngresoFecha", c => c.DateTime());
            AddColumn("public.Candidato", "IngresoTipoContrato", c => c.String());
            AddColumn("public.Candidato", "IngresoVencimientoContratoDeterminado", c => c.DateTime());
            AddColumn("public.Candidato", "IngresoObservaciones", c => c.String());
            AlterColumn("public.Candidato", "AñosDeExperiencia", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("public.Candidato", "FechaDeNacimiento", c => c.DateTime());
            AlterColumn("public.Candidato", "SueldoActual", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("public.Candidato", "NivelDeInglesHablado", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("public.Candidato", "NivelDeInglesEscrito", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("public.Candidato", "NivelDeInglesLectura", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("public.Candidato", "EstatusAcademico", c => c.Int());
            AlterColumn("public.Candidato", "Bolsa", c => c.Int());
            AlterColumn("public.Candidato", "FechaDeContacto", c => c.DateTime());
            AlterColumn("public.Candidato", "Rol", c => c.Int());
            AlterColumn("public.Candidato", "Estatus", c => c.Int());
            DropColumn("public.Candidato", "ApellidoPaterno");
            DropColumn("public.Candidato", "ApellidoMaterno");
            DropColumn("public.Candidato", "CiudadResidencia");
            DropColumn("public.Candidato", "SueldoEsperado");
            DropColumn("public.Candidato", "Nivel");
            DropColumn("public.Candidato", "FechaDeExamen");
            DropColumn("public.Candidato", "HoraDeExamen");
            DropColumn("public.Candidato", "CalificacionDelExamen");
            DropColumn("public.Candidato", "FechaDeEntrevista");
            DropColumn("public.Candidato", "PropuestaEconomicaMonto");
            DropColumn("public.Candidato", "FechaDeIngresoALaEmpresa");
            DropColumn("public.Candidato", "Comentarios");
            DropColumn("public.Candidato", "Rechazado");
        }
        
        public override void Down()
        {
            AddColumn("public.Candidato", "Rechazado", c => c.Boolean(nullable: false));
            AddColumn("public.Candidato", "Comentarios", c => c.String());
            AddColumn("public.Candidato", "FechaDeIngresoALaEmpresa", c => c.DateTime(nullable: false));
            AddColumn("public.Candidato", "PropuestaEconomicaMonto", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("public.Candidato", "FechaDeEntrevista", c => c.DateTime(nullable: false));
            AddColumn("public.Candidato", "CalificacionDelExamen", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("public.Candidato", "HoraDeExamen", c => c.DateTime(nullable: false));
            AddColumn("public.Candidato", "FechaDeExamen", c => c.DateTime(nullable: false));
            AddColumn("public.Candidato", "Nivel", c => c.Int(nullable: false));
            AddColumn("public.Candidato", "SueldoEsperado", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("public.Candidato", "CiudadResidencia", c => c.String());
            AddColumn("public.Candidato", "ApellidoMaterno", c => c.String());
            AddColumn("public.Candidato", "ApellidoPaterno", c => c.String());
            AlterColumn("public.Candidato", "Estatus", c => c.Int(nullable: false));
            AlterColumn("public.Candidato", "Rol", c => c.Int(nullable: false));
            AlterColumn("public.Candidato", "FechaDeContacto", c => c.DateTime(nullable: false));
            AlterColumn("public.Candidato", "Bolsa", c => c.Int(nullable: false));
            AlterColumn("public.Candidato", "EstatusAcademico", c => c.Int(nullable: false));
            AlterColumn("public.Candidato", "NivelDeInglesLectura", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("public.Candidato", "NivelDeInglesEscrito", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("public.Candidato", "NivelDeInglesHablado", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("public.Candidato", "SueldoActual", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("public.Candidato", "FechaDeNacimiento", c => c.DateTime(nullable: false));
            AlterColumn("public.Candidato", "AñosDeExperiencia", c => c.Int(nullable: false));
            DropColumn("public.Candidato", "IngresoObservaciones");
            DropColumn("public.Candidato", "IngresoVencimientoContratoDeterminado");
            DropColumn("public.Candidato", "IngresoTipoContrato");
            DropColumn("public.Candidato", "IngresoFecha");
            DropColumn("public.Candidato", "PropuestaEconomicaComentarios");
            DropColumn("public.Candidato", "PropuestaEconomicaSueldo");
            DropColumn("public.Candidato", "PropuestaEconomicaFecha");
            DropColumn("public.Candidato", "VeredictoFinalComentarios");
            DropColumn("public.Candidato", "VeredictoFinalNivelIdentificado");
            DropColumn("public.Candidato", "VeredictoFinal");
            DropColumn("public.Candidato", "EntrevistaGerenteAreaComentarios");
            DropColumn("public.Candidato", "EntrevistaGerenteAreaFecha");
            DropColumn("public.Candidato", "EntrevistaInglesComentarios");
            DropColumn("public.Candidato", "EntrevistaInglesFecha");
            DropColumn("public.Candidato", "EntrevistaCoordinadorYEquipoTecnicoComentarios");
            DropColumn("public.Candidato", "EntrevistaCoordinadorYEquipoTecnicoFecha");
            DropColumn("public.Candidato", "EntrevistaCapitalHumanoComentarios");
            DropColumn("public.Candidato", "EntrevistaCapitalHumanoFecha");
            DropColumn("public.Candidato", "ExamenPracticoSoporteBdRango");
            DropColumn("public.Candidato", "ExamenPracticoSoporteBdTotalReactivos");
            DropColumn("public.Candidato", "ExamenPracticoSoporteBdAciertos");
            DropColumn("public.Candidato", "ExamenPracticoSoporteBdFecha");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoRango");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoTotalReactivos");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoAciertos");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoId");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoIpComputadora");
            DropColumn("public.Candidato", "ExamenAdministradorProyectoFecha");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasSqlCalificacion");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasSqlTotalReactivos");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasPracticoRango");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasPracticoPuntos");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasPracticoCalificacion");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasPracticoId");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoRango");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoTotalReactivos");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoAciertos");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasTeoricoId");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasIpComputadora");
            DropColumn("public.Candidato", "ExamenIngenieroPruebasFecha");
            DropColumn("public.Candidato", "ExamenAnalistaPracticoRango");
            DropColumn("public.Candidato", "ExamenAnalistaPracticoTotalReactivos");
            DropColumn("public.Candidato", "ExamenAnalistaPracticoAciertos");
            DropColumn("public.Candidato", "ExamenAnalistaPracticoNumeroCaso");
            DropColumn("public.Candidato", "ExamenAnalistaPracticoId");
            DropColumn("public.Candidato", "ExamenAnalistaTeoricoRango");
            DropColumn("public.Candidato", "ExamenAnalistaTeoricoTotalReactivos");
            DropColumn("public.Candidato", "ExamenAnalistaTeoricoAciertos");
            DropColumn("public.Candidato", "ExamenAnalistaTeoricoId");
            DropColumn("public.Candidato", "ExamenAnalistaIpComputadora");
            DropColumn("public.Candidato", "ExamenAnalistaFecha");
            DropColumn("public.Candidato", "ExamenProgramacionRango");
            DropColumn("public.Candidato", "ExamenProgramacionTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionAciertos");
            DropColumn("public.Candidato", "ExamenProgramacionTecnologiaTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionTecnologiaCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionScrumTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionScrumCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionJavascriptTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionJavascriptCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionWebTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionWebCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionLogicaTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionLogicaCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionPooTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionPooCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionAdooTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionAdooCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionUmlTotalReactivos");
            DropColumn("public.Candidato", "ExamenProgramacionUmlCalificacion");
            DropColumn("public.Candidato", "ExamenProgramacionId");
            DropColumn("public.Candidato", "ExamenProgramacionIpComputadora");
            DropColumn("public.Candidato", "ExamenProgramacionFecha");
            DropColumn("public.Candidato", "ExamenPsicometricoObservaciones");
            DropColumn("public.Candidato", "ExamenPsicometricoResultados");
            DropColumn("public.Candidato", "ExamenPsicometricoNombre");
            DropColumn("public.Candidato", "ReclutamientoComentarios");
            DropColumn("public.Candidato", "ExpectativaEconomica");
            DropColumn("public.Candidato", "RolOtro");
            DropColumn("public.Candidato", "BolsaOtra");
            DropColumn("public.Candidato", "FechaRecepcionSolicitudRegistro");
            DropColumn("public.Candidato", "FechaPreentrevistaTelefonica");
            DropColumn("public.Candidato", "FechaDeRecepcionCurriculum");
            DropColumn("public.Candidato", "ProyectoNombre");
            DropColumn("public.Candidato", "PuestoNombre");
            DropColumn("public.Candidato", "PuestoClave");
            DropColumn("public.Candidato", "SolicitudPersonalFolio");
            DropColumn("public.Candidato", "NivelDeIngles");
            DropColumn("public.Candidato", "SoftwareQueDomina");
            DropColumn("public.Candidato", "TecnologiasQueDomina");
            DropColumn("public.Candidato", "CompetenciasOHabilidades");
            DropColumn("public.Candidato", "MotivoDeSeparacion");
            DropColumn("public.Candidato", "Compañia");
            DropColumn("public.Candidato", "GeneralesComentarios");
            DropColumn("public.Candidato", "LugarNacimiento");
            DropColumn("public.Candidato", "EstadoCivil");
        }
    }
}
